### ISSUE TITLE
Provide more details in README

### ISSUE THREAD

**Issue by IrresoluteArkia** [open-horizon-services/Getting-Started#8]
In the sections of the readme for creating new services/microservices, there should be more complete instructions on what message to send in the chat server, and perhaps an example.

A guide or link to getting on the chat server should also be added or linked here, as it is not immediately obvious, and simply clicking the `open-horizon-examples` link will not work if you are not already on the chat server, and this may just confuse new contributors instead.

**Comment by aesop0** [comment]
Hi @joewxboy or @IrresoluteArkia, could you assign me to this issue?
