### ISSUE TITLE
Request to create a repo to house service-liquid-prep

### ISSUE THREAD

**Issue by playground** [open-horizon-services/Getting-Started#9]
Hi @t-fine, we are working to integrate [liquid-prep ](https://github.com/Liquid-Prep/)with OH as a service.

Repo name:  service-liquid-prep
Purpose:  Take Liquid Prep to the Edge
Admin: @playground

**Comment by t-fine** [comment]
@playground `service-liquid-prep` is ready to roll! https://github.com/open-horizon-services/service-liquid-prep
